[botdetection]

ipv4_prefix = 32
ipv6_prefix = 48

# Trust the Caddy reverse proxy on the docker network.
trusted_proxies = [
  "127.0.0.0/8",
  "::1",
  "172.16.0.0/12",
  "10.0.0.0/8",
]

[botdetection.ip_limit]

filter_link_local = false
link_token = false

[botdetection.ip_lists]

block_ip = [
]

pass_ip = [
]

pass_searxng_org = true
